### ISSUE TITLE
Held packages should not be reinstalled when unaffected

### ISSUE THREAD

**Issue by MightyPork** [polygamma/aurman#126]
I might be doing something wrong, as I just switched from yaourt.

In many cases when installing an aur package (possibly always), it reinstalls pacman and glibc for no apparent reason.

Here is my typical command:

```
alias auri="aurman --noedit --pgp_fetch --holdpkg_conf  --noconfirm -S"
```

example output

```none
$ auri anki20-bin
~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: vte-0.28.2-8
:: jade-1.2.1-12
:: otf-cantarell-ib-1:0.0.24-2
:: t1-cursor-ib-1.0.4-2
:: libkexiv2_4-15.08.3-2
:: php-mcrypt-7.1.12-2
:: robomongo-bin-1.0.0-1
:: ttf-oxygen-ibx-1:5.4.3-2
:: libopenssl-1.0-compat-1.0.2.l-3
:: Ignoring installed package terminator
:: Ignoring installed package xf86-input-libinput
:: Ignoring installed package nodejs
:: Ignoring installed package clion
~~ calculating solutions...

:: The following 1 package(s) are getting installed:
   aur/anki20-bin  /        ->  2.0.50-1

:: The following 2 package(s) are getting reinstalled:
   core/glibc      2.27-3   ->  2.27-3
   core/pacman     5.1.0-2  ->  5.1.0-2
~~ looking for new pkgbuilds and fetch them...
```

is there a way to find why this is happening, and what can i do to fix it?

---

edit: found `--needed` which seems to solve the issue for me, but it still looks like a bug

**Comment by polygamma** [comment]
Because of your '--holdpkg_conf' usage. That flag is only meant to be used when it's needed, e.g. you try to update and an update would require the removal of that package. In that case you'd pass `--holdpkg_conf` or the packages you want to be not removed via `--holdpkg`. `aurman` then tries to find a solution, with which the packages remain installed in the end. see: https://github.com/polygamma/aurman/blob/master/src/aurman/main.py#L457

so you may just remove that flag from your alias, and in case of `pacman` and `glibc` you should never need that flag, unless you install e.g. `pacman-git`.

**Comment by MightyPork** [comment]
Oh, you're right, that worked.

but wouldn't the easiest "solution with which the packages remain installed in the end" be to simply not touch the packages at all, if they're otherwise not affected?

**Comment by polygamma** [comment]
It's not quite that easy, since that has to be checked during dependency solving. I guess I am going to introduce a new flag, and change the current `holdpkg` and `holdpkg_conf` so that they really only ensure not getting removed without trying to achieve that with "trying to install". The new flag is going to be the current `holdpkg`, hence: Thanks for your report. Will be changed during the next days, until then just don't use `holdpkg_conf` which really should not be needed in your case anyway. I am going to comment in this issue, when I've changed the behavior

**Comment by polygamma** [comment]
A proper implementation of the holdpkg feature requires in depth changes of the aurman dependency solver with significant performance slowdown, since some assumptions during dependency solving would be no longer true, thus those would need to be checked via calculations. i have decided that this not worth the effort and also not worth the decreased performance, since `holdpkg` is all in all just nice to have, but not really needed. aurman always shows which packages are going to be deleted, hence one may simply not install the packages if something gets deleted which should not be deleted.
