### ISSUE TITLE
Extract dependencies for package base instead of package

### ISSUE THREAD

**Issue by kitsunyan** [polygamma/aurman#129]
## Description
Hi! It seems that aurman extracts `depends` for package instead package base which is not correct for split packages.

For instance, package base `mozc` has 3 dependencies: `depends=('qt5-base' 'ibus>=1.4.1' 'zinnia')`. But package `mozc` has only 2 of them: `depends=('qt5-base' 'zinnia')`. Aurman assumes that only these 2 dependencies are required, but `makepkg` will fail since `ibus>=1.4.1` won't be found.

## Expected Behavior
Aurman extracts `depends` for package base.

## Current Behavior
Aurman extracts `depends` for package.

## Possible Solution
Honestly, I found this bug in aurman when I wanted to check how you solve this problem because I knew you are using AUR RPC instead of `.SRCINFO` parsing. [Here](https://github.com/kitsunyan/pakku/commit/3edef649597b7669bd67b1e42680ac25068debc7) I described how I fixed my `.SRCINFO` parser (under 3rd point), but it seems to be not easy to fix using AUR RPC. It provides neither package base `depends` nor method to query package base info.

## Steps to Reproduce

1. `aurman -S mozc`
```
==> Missing dependencies:
  -> ibus>=1.4.1
```

**Comment by polygamma** [comment]
Thank you very much for your report! Did not know about that... Really ugly problem.
To solve it, I can only think of dirty hacks right now. e.g. search for packages of the same maintainer e.g. https://aur.archlinux.org/rpc/?v=5&type=search&by=maintainer&arg=ponsfoot and look for the same pkgbase, after that merge the dependencies as needed, but hell no, not going to implement things like that.

Really have to think about that, if there even is a nice solution currently, and if there is not, I guess this problem does not arise very often, hence pointing that out in the README could do it for those cases?

**Comment by AladW** [comment]
Related report: https://bugs.archlinux.org/task/57230?project=2

**Comment by AladW** [comment]
That PKGBUILD does some really weird things though, like
```
pkgname=mozc
true && pkgname=('mozc')
```

**Comment by AladW** [comment]
The problematic line appears right at the end:
```
# Global pkgdesc and depends are here so that they will be picked up by AUR
```
WTF?

**Comment by AladW** [comment]
To spam some more and in response to the fancy new tag: this just looks to be a faulty PKGBUILD. Global depends should only be used if they are specifically required for building a package, here it's purely superficial. (and `ibus` 1.5 is in the repos so not sure why it would fail in the first place)

More generally the `pakku` rules seem arbitrary to me or at least I don't see where they are similarly defined in `PKGBUILD(5)`. In the event of a valid example where `makedepends` are defined globally, you could at the end of dependency solving retrieve all `.SRCINFO` files for collected `pkgbase` - each `pkgname` has a corresponding field in the RPC output - then check if the resulting global make/depends contain packages previously undefined or even use these exclusively per `PKGBUILD(5)`. 

The problem with that is it's excessively slow, even if you retrieve things in parallel you're looking at over a half a minute of delay with large dependency chains (typical ROS test case). The only proper way to fix these things (as usual) is to patch the RPC so that it can be queried by `pkgbase`. I'm not sure how hard that is but upstream at least seems willing to accept a patch on that regard.

**Comment by polygamma** [comment]
Short answer to one question since I am sitting in a lecture: It fails because aurman does not use `makepkg -s`, the deps are installed via an explicit `pacman` call. Hence if they are unknown, they are not going to be installed.

**Comment by AladW** [comment]
An addendum to my last comment: I'm wrong that retrieving .SRCINFO files would add an additional delay, since these are already retrieved as part of the `git clone` process. So you could do it in two stages:

1. fetch packages as usual, using AUR RPC for initial dependency resolution
2. repeat dependency resolution but now based on the retrieved .SRCINFO files

> It fails because aurman does not use makepkg -s, the deps are installed via an explicit pacman call. Hence if they are unknown, they are not going to be installed.

Okay but wouldn't a comparison with repo packages take place either way? (I'm probably missing something here)

**Comment by polygamma** [comment]
> Okay but wouldn't a comparison with repo packages take place either way? (I'm probably missing something here)

Which comparison do you mean?

**Comment by AladW** [comment]
Nevermind, I see what you mean now by not using `makepkg -s`.

**Comment by kitsunyan** [comment]
@polygamma I think you can just leave it as it is and mention it readme until API will be updated to query pkgbase. Another option is to create a `.SRCINFO` parsed and use it to extract package info, which is more correct in many ways, but dramatically slower. I don't think adding such hacks as using `search` call is a good idea.

@AladW my rules are not the only true, I made them for simplicity.
```

**Comment by polygamma** [comment]
Have not encountered this problem again, I also forgot to add something regarding this issue to the README. I do not think it's necessary at this point to do so, things may change if users come across this problem.
