### ISSUE TITLE
Allow default `optimistic_versioning`

### ISSUE THREAD

**Issue by HaleTom** [polygamma/aurman#130]
Please add `optimistic_versioning` to the config file (or README)

**Comment by polygamma** [comment]
I am not sure what "or Readme" is supposed to mean

**Comment by polygamma** [comment]
Since you've been active on GitHub during the last two days, but have not responded here, I am going to close this issue.

**Comment by HaleTom** [comment]
I have updated the issue description.

**Comment by polygamma** [comment]
It is not being described as valid config option, hence it is not a valid config option. It will also never be one, since that flag should only be used if needed.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/c80a55c89291f8c764b2774c7a8c145536e48a8a

I've decided otherwise since this will stop requests regarding this feature. I've added a notice, that this is not recommended, and I'll simply close every GitHub Issue which is referable to wrong usage of that flag
