### ISSUE TITLE
Since Microsoft bought Github, have you considered migrating to Gitlab?

### ISSUE THREAD

**Issue by jambonmcyeah** [polygamma/aurman#137]

**Comment by polygamma** [comment]
I have, but I honestly think it's too early to decide something like that.
No idea what is going to change, but since it's Microsoft a migration to something besides GitHub is quite unavoidable I guess.

**Comment by AladW** [comment]
As I mentioned on the boards:

>github is a proprietary service with proprietary code (i.e. javascript), whether or not microsoft is in charge will make no difference in this regard. If you actually care, switch to a servive like savannah.

**Comment by Mauladen** [comment]
And what has changed with the arrival of Microsoft?

**Comment by AladW** [comment]
I suspect they will colorize the logo.

**Comment by AladW** [comment]
In any case: regardless of who takes over what, it's always a good idea to create a backup of your repo with a different hoster. I use repo.or.cz which can mirror a repo automatically:

http://repo.or.cz/aurutils.git

**Comment by polygamma** [comment]
Candy Crush Saga integration incoming

**Comment by Mauladen** [comment]
@AladW The Corporation assured that GitHub will maintain its independence to ensure the further work of an open platform for developers in all sectors

**Comment by Mauladen** [comment]
@AladW What is the problem to transfer to another hosting project when something happens?

**Comment by AladW** [comment]
You'd have to migrate all existing issues, for one, assuming the hosting project supports these in the first place. At least gitlab seems to support this automatically.

https://docs.gitlab.com/ee/user/project/import/github.html

**Comment by polygamma** [comment]
relevant: https://www.linuxfoundation.org/blog/microsoft-buys-github-the-linux-foundations-reaction/

**Comment by jambonmcyeah** [comment]
I just watched Gitlab's video on how to transfer repos. Apparently, Gitlab does a pretty good jobs at transferring repos. It transfers issues and pull requests and it even preserves the tags on issues. 

Video: https://www.youtube.com/watch?v=VYOXuOg9tQI

**Comment by BurhanDanger** [comment]
May be irrelevant : https://www.preining.info/blog/2018/06/microsofts-failed-attempt-on-debian-packaging/

I have trust issue in M$. EEE

**Comment by AladW** [comment]
>May be irrelevant

It is. I do wonder though: did you stop using Valve products after Steam removed the home directory after some update?

**Comment by BurhanDanger** [comment]
I wasn't one of steam's victim. But here the clue word is deliberately. You might favour MS but I don't like giving them control.

MS most likely bought GH because they want influence over opensource. The whole MS embracing opensource is because they have to. This is up for a debate , so I'll see myself out.

**Comment by AladW** [comment]
We as Arch users pride ourselves to only use purely technical arguments for or against something, though, and speculation such as "influence over opensource" is hardly that.

**Comment by kewlfft** [comment]
Tracking developers, using it for commercial purpose, influencing projects is very possible but I am not sure how much more likely it is under MS management than it was before. We need to be pragmatic and not speculate too much. For example, the fact Google tracks us does not prevent many of us to use it, carefully.
This is about being aware and managing it.
Then it is always good to look at alternatives, the pros and the cons transitioning to a more private solution and switch if pros outweigh cons, but rationally.

**Comment by AladW** [comment]
>Tracking developers, using it for commercial purpose, influencing projects is very possible but I am not sure how much more likely it is under MS management than it was before

Right. The license of this project allows commercial use anyway. (though I'd argue commercial use of an ''AUR helper'' is close to 0%)

>Then it is always good to look at alternatives, the pros and the cons transitioning to a more private solution and switch if pros outweigh cons, but rationally.

The only private solution I know of that offers the same or comparable feature set as github is hosting your own gitlab instance. However besides the monetary cost - you'd definitely at least a higher end VPS to even get it running - there's the additional maintenance.

Maybe you can find some different hoster with terms of service but when those change, it's the same issue all over again.

**Comment by jambonmcyeah** [comment]
You could always use Gitlab's public solution. Hosting is free same as Github and Gitlab comes with their own CI.

**Comment by ChrisKitching** [comment]
> You could always use Gitlab's public solution. Hosting is free same as Github and Gitlab comes with their own CI.

I wonder if gitlab's rather nifty free CI would be a way to reduce the maintenance burden of this project, too? Stuff like automating pushing of PKGBUILDS when new `pacman` moves from testing to core. Automated tests are also a great way to reduce the amount of hatemail people send you ;)

I'd be more than happy to help set that up if you're interested: drop me an email or something.

**Comment by eli-schwartz** [comment]
The what what?

Why does a new PKGBUILD need to be pushed when pacman moves from testing to core? There's nothing to rebuild, since aurman is not a C program linking to libalpm.so

Any code changes needed, cannot be pushed in an automated manner without someone first writing it.

Also Travis CI is just as theoretically capable of this??? I'm assuming you're referring to daily cron jobs...

Also, it would require giving CI access to the SSH private key tied to @polygamma's AUR account, this sort of secret sharing in general is the kind of thing one tries to avoid when not strictly necessary. Which this isn't since I still don't see any use case whatsoever.

**Comment by ChrisKitching** [comment]
> Why does a new PKGBUILD need to be pushed when pacman moves from testing to core? There's nothing to rebuild, since aurman is not a C program linking to libalpm.so

I was alluding to one of the things mentioned in #140: a change was written for aurman that depended on a newer pacman. The maintiner of this project got a bunch of angry messages because he wasn't "fast enough". It would in principle be possible to set up automatic deployment of the new version (after it passes tests) in response to the necessary upstream dependencies going live.

> Any code changes needed, cannot be pushed in an automated manner without someone first writing it.

This is what staging is for: you can push your changes when written, configured to be deployed when (for instance) the newer version of something upstream you want is available.



> Also Travis CI is just as theoretically capable of this???

I never claimed it wasn't. One nice feature of gitlab is its "manual" CI tasks that allow triggering of subtasks from the UI (often for deployment). Such things can query you for things like key passphrases, which answers your subsequent question, too.



> I still don't see any use case whatsoever.

Automated testing is useful for many things. I ended up coming here after the last update to aurman led to it crashing with `-S` in a clean environment. It would be useful to have some kind of CI to catch stuff like that, so I offered to lend a hand.

It's also somewhat unhelpful to snap like that at someone who has come here to be constructive and offer to help. Just because you can't immediately see the merit of my suggestion does not mean it's OK to adopt such an aggressive tone.

**Comment by eli-schwartz** [comment]
Right, but Travis CI on Github is **already used** and can simply have its cron jobs setting toggled. Also development is more or less daily, and he got angry messages within minutes of the new pacman, not within days -- cron jobs cannot help with that, and automated deployments hooked to that cron job would have resulted in a dramatically *slower* response time, necessitating deployment by hand anyway.

(BTW Travis dashboard tells me daily cron jobs are already in fact active.)

> Automated testing is useful for many things. I ended up coming here after the last update to aurman led to it crashing with -S in a clean environment. It would be useful to have some kind of CI to catch stuff like that, so I offered to lend a hand.

I am definitely not suggesting CI in the general case is pointless! Just using it to deploy changes you haven't written yet...

aurman does not test unreleased versions of pacman-git.
aurman also does not test its own new features when those are explicitly disabled in the docker tests, and aren't very testable in the first place (besides the news using a prompt that absolutely requires an interactive tty -- @polygamma wants it to not depend on newlines to read answers).

None of this matters, because it's the generic concept of CI which is offtopic for a "consider migrating to gitlab" issue -- if you want to discuss general CI, please open a new issue.

**Comment by ChrisKitching** [comment]
> cron jobs cannot help with that

I never mentioned cron: I was thinking more along the lines of a hook triggered by the event of interest. It's definitely possible for CI systems to deploy things within "minutes", but I take your point that this isn't the most useful thing to bother doing.

> Just using it to deploy changes you haven't written yet...

As I pointed out in my last message, this is (freaking obviously) not what I was suggesting. I was proposing the (not exactly unusual) situation where code is pushed to CI, tested, and deployed at some later time when conditions are satisfied.

If you can design a CI system that deploys changes that haven't been written yet, I want to buy it. It will presumably save vast amounts of developer time by doing their job for them.

> aren't very testable in the first place

The "aurman crashes if `~/.aurman/cache` does not exist" issue is the specific issue I claim could be easily caught by CI. You probably want to add a test that runs aurman in a completely clean environment to catch situations like this.

> besides the news using a prompt that absolutely requires an interactive tty

Note that you can automate testing of things that require an interactive tty by using `socat`, something along the lines of `socat -lf /dev/null -du EXEC:"aurman ...",pty,ctty,stderr STDOUT`, and then you pipe in the sequence of button presses you want to input for your test. The program under test believes it's talking to a tty, and hence you're able to pipe stuff through "interactive mode" of your program and test it.

> @polygamma wants it to not depend on newlines to read answers

My suggestion here would be to check if stdin is an interactive terminal. If it is, do the current behaviour. If not, change the behaviour only by no longer having default replies to any prompts (such that sending an "enter" just gets you the prompt again). This would be sufficient to make things like `yes` work correctly. You could alternatively simply disable the "no newlines for answers" behaviour entirely in non-interactive mode.



I appreciate we are now offtopic. I originally replied to the commenter above my original post (which was relevant to github), and now we've ended up talking about four different things at once in a somewhat hostile tone.

Regardless, it seems clear that contribution is not welcomed. Best of luck with it all.

**Comment by polygamma** [comment]
> The "aurman crashes if ~/.aurman/cache does not exist" issue is the specific issue I claim could be easily caught by CI. You probably want to add a test that runs aurman in a completely clean environment to catch situations like this.

It was just unlucky, because I disabled exactly that feature in the docker tests, in general those things are covered by docker tests. Did not think about it enough, my fault, but that's it.

**Comment by polygamma** [comment]
I am currently not thinking about actually moving to Gitlab, I may reopen this issue if that changes sometime.
