### ISSUE TITLE
aurman sucks, you suck, you are a bad programmer, aurman should be deleted from the wiki table since it is not working 90% of the time

### ISSUE THREAD

**Issue by polygamma** [polygamma/aurman#140]
Lately I am receiving more and more messages, the worst ones via email (obviously), criticizing aurman itself, me as software developer and as person in general. Hence I am making the following statement once, there will be no other statement regarding this problems.

First the kind of "objective" criticism, not cited word by word, but what the people meant:

> "You shithead broke aurman twice during the last week, at first you have not been able to release aurman in a proper way for pacman 5.1, second you are too dumb to get your dependencies right, an urllib3 update broke aurman again.

pacman 5.1 had been pushed to "staging" with an announcement on reddit, whereas pyalpm, a dependency of aurman at that point, failed to build. see [reddit comment](https://www.reddit.com/r/archlinux/comments/8mlj5l/release_notes_for_pacman_51/dzomadx/) and [github issue](https://github.com/jelly/pyalpm/issues/4)
I did not know at that point, when pacman was going to hit "Core", hence I had to make the following decision: Hope that pyalpm gets fixed for the pacman release, so that everything is fine, or remove the pyalpm dependency so that a pacman 5.1 release with broken pyalpm does not break aurman.
I decided for the latter, see: [remove pyalpm issue](https://github.com/polygamma/aurman/issues/107)
Now there was the problem with a versioned pacman dependency, "new" aurman not working without pacman 5.1 due to the usage of pacman-conf, and "old" aurman not working with pacman 5.1 due to the failing build of pyalpm at that point. As suggested by @AladW I updated the PKGBUILD of the "old" aurman `pacman<5.1` and prepared the PKGBUILD of the "new" aurman `pacman>=5.1`. I obviously did not push the "new" aurman because I did not know when pacman 5.1 would hit "Core".

pacman 5.1 was pushed to "Core" in the same night (german time), I woke up because of my non stop vibrating smartphone, since I received direct emails, notifications of github and aur.archlinux.org, reminding me that I may please release the new PKGBUILD, which is perfectly fine. I got up and released that PKGBUILD, see: [aur.archlinux.org commit](https://aur.archlinux.org/cgit/aur.git/commit/?h=aurman&id=eea3fefd037891177bef8cb1ba11339fb8ba8341)

Later that day I started receiving the first emails mentioning my incompetence to handle a pacman update in a proper way, because users have not been able to solve the following "problem":
`:: aurman: installing pacman (5.1.0-1) breaks dependency 'pacman<5.1'`
Well, obviously that is not a "bug" or a "problem", just an occasion where the user has to do something manually, namely "remove aurman, update the system, install the current aurman version". But yeah, I guess I should stop developing software.

Now for the second time at which I broke aurman.
The update of `python-urllib3` - [archlinux.org commit](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/python-urllib3&id=cb7c48d0b4b7e74414aa06131f9c4ddcb657e6eb)
aurman uses `python-requests` as direct dependency for the AUR RPC queries. The current `python-requests` version 2.18.4 depends on `urllib3<1.23`, whereas `urllib3 1.23` had been released. A few hours later, the `python-requests` arch package got a new pkgbuild, see: [requests version bump](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/python-requests&id=cd793259b3595b148a05f7c238aaf97327503454) with a small, dirty hack to change the versioned dependency. That lead to `python-requests` being usable, but still emitting a warning after executing a python program using it. See: [python requests pull request](https://github.com/requests/requests/pull/4671/files ) which is needed, to also remove the warning.
As you can see, it was totally me who broke aurman, again.

There was a comment on the aurman aur.archlinux.org page mentioning how unstable aurman is, hence i should start to test my software instead of releasing "patches" every day. Obviously I do test aurman, and those "patches" are mostly new features as requested by users. There are a few bug fixes, sure, and I do agree that it is unusual to release a new aurman version that often, but I want to keep it that way, since this is Arch Linux and not Debian. If one does not like frequent updates, do not use Arch Linux or use `--ignore aurman` when updating.

Now for the "not objective" criticism. I'm an asshole, should stop developing open source software, and should admit that aurman is shitty instead of closing issues on github, just because i am not able to fix complex things. I am honestly not even sure which issues that is referring to, but well, okay.

I am developing aurman for myself, in the first place. I used pacaur, which is no longer being developed, hence I looked for a replacement and decided to write my own AUR Helper. I am using open source software for many years and like the idea behind it, so I decided to work on aurman as an open source project with a MIT license. I am always grateful for bug reports and sensible feature requests, but I am simply not going to implement everything users want. I do this in my free time, if I can't find motivation to implement some thing like support for other languages or zsh completion, I am simply not going to do it. In those cases it has nothing to do with "I don't want to see this feature in aurman" but simply lack of motivation to implement those things. Anyone may implement those and open a PR, as I have written in the regarding issues.

For other features I simply do not want to implement them, because I would never use them and I personally do not the see general usecase. In those cases I'd also not merge PRs, which you may dislike, but because of that I released aurman under the MIT license. Everyone may fork aurman and implement features as many as wanted, deal with it.

Final words: I really like working on this project, I've learned a lot and met many nice people. I've also received many nice comments, emails etc, which I really appreciate, but lately I start to lose motivation, because of all this bullshit. I do not want to stop working on this project in the way I am doing it right now, but I also do not want to deal with this negative shit. Hence I'll simply **not** respond to any kind of those things, be it rude comments, not using the issue template for bug reports or not reading the readme. I'll simply close those issues, delete comments and ban users from this repository in case of repeatedly doing those things. If you encounter your issue to be closed and you really don't know why, just email me or explain in detail in the issue why you think closing it was wrong. I'm not a monster, but I'll start handling this repository in a different way from now on. If you want bugs to be fixed or new features to be implemented, I guess it's not too much to ask for writing more than one sentence which doesn't even really explain what you want, since all in all I've got the work to fix and implement things, not you, unless you provide a PR.

**Comment by AladW** [comment]
As I pointed out before it's the nature of the beast. When you write an AUR helper that 

* can be used without enabling Brain 1.0 and 
* that becomes "Best Buy" due to coincidental changes on ArchWiki, 

both project and its author become a honeypot to users that are demanding yet unwilling to contribute back in any contructive way. In other words, the kind of users that Arch explicitely does not target but still reach due to derivates and other reasons. 

In short `aurman` became the new `pacaur` and now you're dealing with same shit @rmarquis did. I completely side-stepped these issues by leaving out the last few layers of abstraction in `aurutils` - making the software unusable to the above described user base - as well as long release cycles with the last aurutils release was over a year ago.

Maybe by cracking down (read: banning users) both here on github and on the AUR page that things will slightly improve in future. Not for emails probably, but you can do as me and change your public email address to `devnull@archlinux.org`. :wink:

**Comment by AladW** [comment]
And to add some historical context... the exact same thing happened to Arch Linux ARM too. Take a look at their github tracker if you're interested.

**Comment by rmarquis** [comment]
The above sounds indeed quite familiar...

@polygamma I have no real solution to bring here, apart from what has been already recommended above. I am however able to give you this little advice: take time for yourself, even if that means being away from your project for a few days. Read about "open source burnout" and learn to detect its symptoms early. It's much more difficult than it seems - I wasn't aware of it and it burnt me more than a few times.

**Comment by ognarb** [comment]
Some people probably never read the software licence of the program they use.  Sometime you need to remind them.

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
> IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
> FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
> AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
> LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
> OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
> SOFTWARE.

**Comment by HaleTom** [comment]
Thank you for creating such a great tool, and sharing it with the world.  It's generally a thankless job. It doesn't mean it's not greatly appreciated.

THANK YOU for your time and energy you put into this.

**Comment by emvigo** [comment]
I'll just say this: Thanks for your work. And again, this is YOUR project, so it is YOUR rules.

**Comment by grm34** [comment]
Thank you for the job, i use this helper since pacaur unmaintened and like you said, we are on arch, so people wich cry for stability can simply move on debian :)

**Comment by kewlfft** [comment]
I wonder why people release their anger on AUR helpers more than on any other projects. This is a bit like someone insulting his servant because he cannot handle a situation. 
The offer of helpers is huge and an unhappy user can easily switch to another project.
Therefore these complaints are purely irrational and should just be ignored. You are not imposing to anybody aurman and we take our responsibilities using it.
Arch philosophy is also about being responsible about our system, the tools we use and deal with the consequences.

Thanks for aurman and keep doing things your way which should continue to please many users.

**Comment by cryzed** [comment]
Hey, we've talked before via e-mail! I still love aurman and am really glad that you decided to publish it for us to use. Please don't let the unhelpful negativity get you down; I think your new approach to this is perfectly sensible!

To the people who would rather throw insults instead of doing something actually helpful, i.e. proper bug reports or alternatively pull requests fixing _your issue_: just use a different AUR helper! I don't even necessarily mean this in a spiteful way -- there are a bunch of them. If none of them suit you, maybe you are the problem :1st_place_medal: .

**Comment by eli-schwartz** [comment]
Hmm, users to indeed tend to suck quite often.

That being said, I do feel sort of vindicated in my belief that versioned dependencies suck too. They're especially issueful in that normally the fix for a broken AUR package is "rebuild it", but versiones dependencies make that rather difficult. At least soname dependencies can actually be resolved by building in a clean chroot...

As for the pacman-conf thing, I solved that in devtools by falling back on pacconf from pacutils if the pacman-conf binary is not available... which has been available for some time. Unfortunately said devtools patch did not get merged until after Pacman 5.1 was already released, but oh well, I did try.

(The fix there would be to depend on pacutils until after Pacman 5.1 was released, since an extra dependency does not hurt anyone, and skip the versioning of dependencies. Leaving you to remove the extraneous dependency at your leisure following the general release of Pacman 5.1)

**Comment by polygamma** [comment]
also relevant: https://github.com/polygamma/aurman/commit/dae2b6489166f2412f0197234550088680090f41

**Comment by AladW** [comment]
What's the least amount of clicks: banning users or closing issues? Or can you automate this via the GitHub API? :smile:

**Comment by polygamma** [comment]
@AladW - I prefer banning: https://github.com/polygamma/aurman/issues/175#issuecomment-398676797

regardless of the amount of mouseclicks

**Comment by polygamma** [comment]
I guess someone is mad: [reddit thread](https://www.reddit.com/r/archlinux/comments/8sh1r9/be_careful_if_you_create_an_issue_for_aurman/)

**Comment by AladW** [comment]
For your convenience: https://developer.github.com/v3/users/blocking/

**Comment by dcousens** [comment]
@polygamma you're doing a great job!  As an OSS maintainer myself,  and having seen this a few times, I'd recommend asking anyone who can help, to help,  maybe let a group of helpers maintain/moderate issues as a buffer before you.

**Comment by spudshack** [comment]
Hi there
Do not worry about people who are not worth worrying about. I also find it depressing to see the level of childishness computer science has sunk to on some forums. It's your project, you do what satisies you and release it whenever you want. Put other people's demands on a list. Treat development as one block at a time, and when you are happy with one block, only then move to the next. Your English is very good, in fact better than most Americans is ( only joking)  besides you're studying computing not linguistics. Apart from contributing to the Linux world, you're getting something extremely valuable out of this that few undergraduates and often some programmers never get. Dealing with customers. I use the word customers a loosely here, but the experience is invaluable. I had a friend who once turned to a customer and shouted 'what do you expect it to do....tell jokes?'  Good luck with your exams.

**Comment by balliegojr** [comment]
Hi there

It is really impressive to see people complaining about aurman.
1. If they have the knowledge, they can send a PR to fix the problem
2. they can just change to another project
3. If you use aur helper, you are lazy, and you should know about it.

I use aurman since March, because I am lazy and aurman is very good, they day I started to use it I saw a problem, it wouldn't install on my raspberry, after some research I saw that it was necessary to change the architecture in the PKGBUILD file to install it, after successfully installed, I came to github to suggest the change, which the developer accepted and changed very fast.  

Did I have problems with aurman after that? yes, I did. I've waited till the problem was fixed. If is really necessary to update a given package, one can always update it manually.
Did I have problems with other packages? yes, I still have, it happens all the time. Dependencies are hell to maintain, people should know better, it is not the developer fault.

**Comment by Margular** [comment]
Don't be sad,we stand up for you

**Comment by polygamma** [comment]
I guess it's time to close this issue... Things really have settled down over time, thanks to the revised README and Issue template but most of all @eli-schwartz who is helping me with the GitHub issues.

Anyway: Thank you very much for all the nice comments in this issue and the emails I received. As one may see when looking at the commit history, I definitely got my motivation back

![screenshot from 2018-07-19 18-15-36](https://user-images.githubusercontent.com/20651500/42956251-c8db9292-8b7f-11e8-8e46-70f73216829a.png)

**Comment by zirou30** [comment]
Do not discourage friend and thanks for the excellent tool, this project is good and will improve even more I believe. Sorry my english google translator lol.
