### ISSUE TITLE
In depth wiki article, explaining what `aurman` does ?

### ISSUE THREAD

**Issue by polygamma** [polygamma/aurman#156]
see: [AUR_Helper Talk](https://wiki.archlinux.org/index.php/Talk:AUR_helpers) and [GitHub discussion](https://github.com/actionless/pikaur/issues/201)

It is being discussed quite heavily, which risks are involved due to the usage of AUR Helpers.
The [wiki table](https://wiki.archlinux.org/index.php/AUR_helpers#Active) is under continuous improvement, to state from a technical point of view, which risks are involved, but this complex problem is hard to break down to a few colors in a table.

If wished by users, I'd write a kind of in depth article, explaining what `aurman` does and how `pacman` is being executed. Also, how different flags like `--do_everything` change the behavior.

Please give feedback, if this is wanted or not, and if so, which specific questions should be covered by the article.

Edit: Compare with [dependency solving explanation](https://github.com/polygamma/aurman/wiki/Description-of-the-aurman-dependency-solving), just for `aurman` in general.

**Comment by norg** [comment]
As I just switched from yaourt to aurman, such an article would be very helpful!

**Comment by AladW** [comment]
More details always help.

**Comment by polygamma** [comment]
> More details always help.

Does that include more details about my beard?

**Comment by polygamma** [comment]
I had planned to write this over the next days, but besides "thumbs up" I have not received any concrete questions to be answered. It would be nice, if people are interested in such an article, to give a bit more information about what they want to know.

**Comment by rmarquis** [comment]
I feel this is difficult to write because you can't really explain why aurman does X in a certain way without referring to the history of past design, their pro and cons which eventually lead aurman to the choices of the current designs (both on the solver and installation parts). Over time, the 'complete' helpers moved from solving and installing packages sequentially by reading PKGBUILD (f.e. yaourt) to pre-computing everything through the RPC interface and batching the steps (aurman, yay). Such article would be a technical chronology.

As a side note, I do feel such article would be interesting, but to an extremely niche audience only. Beside helper writers, most users absolutely don't care about how helpers work past makepkg steps (for those that have the technical pro-efficiency to use Arch), and those that do are the ones that write helpers.

**Comment by AladW** [comment]
Arguably such a chronology would mirror the developments of the AUR: make/depends in RPCv2 allowed easy a priori computing of dependencies, `git` support in AURv3 allowed easy viewing of diffs, and so on. Leaving those aside, "classic" helpers like aurman, yay, pacaur still follow the original yaourt design quite closely. (Unfortunately, yaourt itself never caught on AUR developments.) In that sense I agree that (the excellent) documentation on the solver - aurman's main distinguishing feature - is already sufficient.

Maybe there's some overlap with the `aurhelper(7)` man page I'm writing, which includes a chronology of sorts and builds an example implementation step by step. (Said implementation more follows aurman & co. than new designs like aurutils.) 

If more than 1 person is interested in such a document, perhaps we could collaborate on it. :slightly_smiling_face:

**Comment by AladW** [comment]
Right now people have the following options when they want automation with the AUR:

1. Keep usage of AUR packages limited so that manual steps suffice or can be concatenated in a small script;
2. Use any of the available AUR helpers as a black box.

"black box" because all current helpers have grown to be highly complex projects, to the point where you might as well start from scratch rather than understand their respective codebases. That's where `aurhelper(7)` would come in: start from the small use case (point 1.) and gradually build up to handle more complex scenarios.

I should have a draft somewhere, hopefully not in data heaven...

**Comment by polygamma** [comment]
It's been almost three weeks since my last post in this issue, I guess @AladW and @rmarquis are right, it's not really worth the effort to write such an article for `aurman` only. I am however interested in helping with the `aurhelper(7)` man page. I'll thus close this issue, but @AladW may write me a message e.g. on reddit, if there's something to do regarding the mentioned help page.
