### ISSUE TITLE
Dependancy expac has been moved to Extra repository

### ISSUE THREAD

**Issue by agsimmons** [polygamma/aurman#160]
It appears that expac is now an official package in https://www.archlinux.org/packages/extra/x86_64/expac/ . It has been removed from the AUR, so aurman now requires expac-git. The Extra package should probably be used instead.

**Comment by polygamma** [comment]
That is not even close to what happened. https://github.com/falconindy/expac/pull/35

**Comment by polygamma** [comment]
Sorry, was in a rush. expac is in the repos for a long time, aurman also used expac from the beginning. I wanted to implement proper support for "replaces", which is not possible with the current expac version, since that version strips the versioning from the "replaces" strings, as being described in the issue behind the linked PR. the PR has been merged, is hence available in expac-git, but not expac, until a new release is being pushed. after that has been done, aurman will depend on expac again

**Comment by AladW** [comment]
To reduce noise you could use an "ifdef" and add a note in the readme.
```
if expac_version >8
  handle_replaces
else
  don't
```

**Comment by polygamma** [comment]
I do not want to touch the sourcecode of `aurman` for that, it's not like using `expac-git` really is a big deal. If one wants to use `aurman`, he will install `expac-git`, if he does not want to use `aurman` just because of the `expac-git` dependency, well, not my problem. And regarding the README: The **relevant** people, i.e. those opening an issue for that kind of **problem** do not read it anyway.
