### ISSUE TITLE
Accept first option when multiple providers are available?

### ISSUE THREAD

**Issue by Grindv1k** [polygamma/aurman#167]
Hi. Sorry if I have misunderstood the `README` or the available options.

I am using `--noconfirm` and `--noedit`, as I want to install lots of stuff without interaction.

When multiple providers are available, I have to choose one, halting automation.
I would like to simply choose the first option.

Is this possible?
If not, feature request?

**Comment by polygamma** [comment]
Also, see: https://github.com/polygamma/aurman/blob/master/src/aurman/classes.py#L1547

If you yield the exact name of a provider for a dep, of which multiple providers exist, `aurman` is going to choose that provider. So if you know beforehand, that there is going to be the choice between, "ProvA" and "ProvB", simply mention "ProvA" as to be explicitly installed, then `aurman` is going to choose that. Otherwise there is no such "first" provider, hence `aurman` will never choose an provider at random. I guess there is nothing much to say, but we'll see, after you provided an example.

**Comment by Grindv1k** [comment]
`aurman -S eclipse-cpp --needed --noconfirm --noedit` triggers three different choices for me, depending on which `jdk` version I want.

This is on a pretty clean Manjaro install.
I now realize that in my case, if I satisfy this dependency before installing `eclipse-cpp` I can probably get away with my problem.

I earlier thought they were all equal but now I see they provide different versions so a random choice would not make sense really.

Thanks for your reply.

The issue is resolved for me.
