### ISSUE TITLE
Question about dependency expac-git

### ISSUE THREAD

**Issue by Crandel** [polygamma/aurman#175]
For aurman you use dependency `expac-git`. It was **Last Updated: | 2015-07-04 17:46**. In *Extra* repository we have updated [expac](https://www.archlinux.org/packages/extra/x86_64/expac/) (**Last Updated: | 2018-05-28 22:18 UTC**). Can you change this dependency to latest version?

**Comment by yan12125** [comment]
FYI: the lastest person with a similar question was banned from this repo (https://github.com/polygamma/aurman/issues/170).

To achieve your goal, expac should release a new version. Please check out details at https://github.com/falconindy/expac/pull/35.

**Comment by Crandel** [comment]
I don`t know anything about this. There are no mentions about expac in README

**Comment by polygamma** [comment]
You may even use google to find out about this by now. Searching for e.g. `aurman expac` or `aurman expac-git` yields what you needed to know. You could have also searched in recent issues, have looked at https://aur.archlinux.org/packages/aurman or what would have been the best: Used your brain. Obviously `expac-git` is not outdated, because it is referring to the master branch of the expac repo, hence your "bug report" is wrong. I am too annoyed by these things, opening Issues with exactly zero effort to have researched **anything**, hence you have been banned, too.

**Comment by Cradleman** [comment]
You blame this guy to google something? Why should he spend his time to do this? Because you  are so lazy to update **README** file? I checked open issues and didn`t see anything about this stupid dependency. You even don`t have a dependency description. "Very good" attitude for your users.

**Comment by polygamma** [comment]
And you have been banned, too.

**Comment by kewlfft** [comment]
@Crandel opening a @Cradleman account just to be able to insult an open source developer? Man take a step back and think how you ended up in this situation.

**Comment by polygamma** [comment]
That escalated quickly: https://www.reddit.com/r/archlinux/comments/8sh1r9/be_careful_if_you_create_an_issue_for_aurman/
