### ISSUE TITLE
rebuild and reinstallation of multiple dependent packages happens in random order

### ISSUE THREAD

**Issue by steven-omaha** [polygamma/aurman#177]
## Description
When you have installed two packages A and B, with B depending on A, and you want to rebuild and reinstall both packages, sometimes aurman installs B before A, and sometimes A before B. This is unexpected, because the order of the dependencies is handled properly when A and B are first installed with aurman.

This is especially a problem with AUR-packages like `openblas-lapack` and `python-numpy-openblas`, where `openblas-lapack` may depend on some numerical libraries in the repositories, and `python-numpy-openblas` depends on `openblas-lapack`. When a library from the repositories has a major change, the user has to recompile and reinstall both packages in the proper order to prevent breakage.

## Expected Behavior
When `aurman -S --rebuild A B`, with A and B in the AUR, and B depending on A, aurman should first build and install A, and then build and install B.

## Current Behavior
When `aurman -S --rebuild A B`, with A and B in the AUR, and B depending on A, aurman builds and installs A and B in random order.

## Possible Solution
Apply the ordering of packages for newly to-be-installed packages also to the packages that are to be  `--rebuild`.

## Version of aurman you are using
2.13-1

## Steps to Reproduce
This uses for example cower and pacaur, because these have very small build times.
1. have `cower` and `pacaur` installed by any means.
2. `aurman -S --rebuild cower pacaur`
3. When asked to continue, confirm.
4. aurman then randomly either builds `pacaur` or `cower`. When it builds `pacaur`, terminate with `Ctrl-C`, and go to step 2. I have needed up to 5 retries to cause the effect.

A pastebin is provided [here](https://pastebin.com/bSMBFaKH).

## Read the README
I did.

## Running linux distribution
Arch Linux.

**Comment by polygamma** [comment]
I see, you could use `--deep_search`, because the dependency solver is going to calculate the dependencies as if none of them would be installed, hence the order of rebuilding should always be correct. I am currently not at home, may you try that out?

**Comment by steven-omaha** [comment]
Thanks for responding quickly.

`--deep_search` does something completely different, and causes not touching the installed packages at all.

	$ aurman -S --rebuild --deep_search cower pacaur
	~~ initializing aurman...
	:: Ignoring installed package texlive-bibtexextra
	~~ calculating solutions...
	
	:: The following 1 package(s) are getting installed:
	   extra/expac                   /                 ->  8-2
	
	:: The following 2 package(s) are predicted to get removed:
	   aur/aurman                    2.13-1            ->  /
	   aur/expac-git                 8.1.g5ae006f-1    ->  /
	:: Package expac-git will be removed due to a conflict with expac
	:: Dependency expac-git>=8.1.g5ae006f of package aurman is not fulfilled
	
	?? Do you want to continue? Y/n:

**Comment by polygamma** [comment]
Ah, yeah, I see what's happening. So... If you use `aurman` without `--deep_search`, `aurman` is going to look at the packages installed on your system, to see which dependencies are unfulfilled. Since you have the package you want to rebuild already installed, the dependencies are already fulfilled, so it does not matter, in which order to install/rebuild, which is in fact true, if you only look at the dependencies itself, hence no bug. That it actually may matter in reality, is not possible for `aurman` to detect, unless versioned dependencies are being used after updates. Now `--deep_search` comes into play, in that case `aurman` does not look at your installed packages, and solves the problem for a system with 0 packages installed. In that case packages to be reinstalled are not shown in the overview, to not show redundant things, hence the weird output. `--solution_way` shows what exactly would happen. Since `cower` depends on `expac`, and `--deep_search` solves the problem not looking at your system, it wants to install `expac`, not `expac-git` and thus removes `aurman`. In that case one would use `--holdpkg aurman-git`, which will fail, because `aurman` depends on a specific `expac-git` version, not known before actually building the package, thus `aurman` will fail to solve the problem. Oh man, what a shitty problem. All in all `aurman` is working as expected. But I've got an idea how to solve this in a proper way, in that case you do not need `--deep_search`, just the regular `--rebuild` usage would suffice, if you yield all packages to rebuild on the command line. Let me try it out, will respond here, when I have done so.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/4ea000348600afb7454c592de15bb008a0ebde80

may you install `aurman-git` and try if it works as expected? Just execute your normal `--rebuild` command, including all the packages you want to be rebuilt, no `--deep_search` needed.

**Comment by eli-schwartz** [comment]
> Since cower depends on expac, and --deep_search solves the problem not looking at your system, it wants to install expac, not expac-git and thus removes aurman. In that case one would use --holdpkg aurman, which will fail, because aurman depends on a specific expac-git version, not known before actually building the package, thus aurman will fail to solve the problem. Oh man, what a shitty problem.

That seems incorrect.
It is trying to calculate for a system where both pacaur (specified on the command line) and aurman (a pre-existing package) are installed, right? But one depends on expac-git and the other depends on expac. And expac-git is one candidate package which fulfills the requirement on expac, satisfying pacaur.

It is therefore unnecessary to remove expac-git and aurman at all, and aurman should try to solve for the system that doesn't entail removing packages.

**Comment by polygamma** [comment]
`--deep_search` ignores what's installed on the system, hence does not know about `aurman` and thus the `expac-git` dependency.

**Comment by steven-omaha** [comment]
@polygamma It seems to work. Thanks!

**Comment by polygamma** [comment]
`aurman 2.13.1` includes this enhancement, hence you may switch back to `aurman`

**Comment by steven-omaha** [comment]
Ich bin wirklich beeindruckt. Mit einer ersten Reaktionszeit von 3 Minuten, einem Fix innerhalb von 40 Minuten und einem Release nach etwa 5 Stunden habe ich wirklich nicht gerechnet. Hut ab, dass Du Dir die Mühe machst und so ein "nebensächliches" Problem so schnell behebst! Vielen Dank dafür!

**Comment by polygamma** [comment]
Gerne! Bei sinnvollen Feature Requests oder Bug Reports bin ich immer sehr motiviert, mich darum zu kümmern. Wenn mir Probleme in meiner Software bekannt sind, sollen diese gerne schnell verschwinden. Aber nochmal Danke für die netten Worte, zwischen den ganzen Flames sehr erfrischend, auch mal sowas zu lesen.
