### ISSUE TITLE
Ability to list upgradable packages from the AUR without sudo  (equivalent of checkupdates or pacaur -k)

### ISSUE THREAD

**Issue by wjstarrsiii** [polygamma/aurman#183]
Hello,  first of all let me say that this has been a great replacement for pacaur for me.  I wanted to see if it would be possible to squeeze in one bit of functionality that I have not been able to replace yet:

I wrote my own package update notifier that runs in my i3 status bar with i3blocks.  It relies on commands that do not require root privileges to list available updates.  For repo packages is uses the checkupdates pacman helper script.  For the AUR, it used to use the "-k" option on pacaur which would report out updateable AUR packages without sudo.

For aurman I only  see the -Su option, which gives me the output I expect but requires sudo.  

Is there a way to do this that I am not seeing, and if not would this be a feature you would consider adding?

Thank you very much for your time,

Bill Starrs

**Comment by Morganamilo** [comment]
`pikaur -Qua` is probably what you want.

**Comment by Morganamilo** [comment]
Whoops wrong repo. See #176.

**Comment by polygamma** [comment]
The issue mentioned by @Morganamilo is the correct one to mention. The feature is available implicitly in the dependency solver. But I would like to add, that I think, one should not use the dependency solver for update notifications. You are creating unwanted traffic towards the AUR RPC. Please do not do that. If you want to install updates, execute aurman, that should be it.

**Comment by wjstarrsiii** [comment]
So it is invalid to wish to see what packages are available prior to upgrading? Or this is a feature that you do not personally find interesting?  Do all of these "check update" type scripts hammer the servers for little benefit?  Forgive my ignorance on the matter, just trying to understand the reasoning behind it.

**Comment by eli-schwartz** [comment]
Aurman already shows you available updates, then asks you interactively if you wish to continue.

As for hammering the AUR servers for little benefit, one could debate whether there's benefit to statusbar notifiers, but the main issue is the kind of statusbar notifiers which ping the server every 5 seconds. The aurweb backend had to be taught how to blacklist IP addresses and emit http 429 "too many requests" errors once people go over the new API rate limit, in order to combat this. This was also especially an issue for people using badly designed AUR helpers which did not know how to send multiple requests in one query via the multiinfo interface... But aurman implements multiinfo anyway.

@polygamma's personal beliefs on the *value* aside, from the perspective of the AUR developers and Trusted Users there is no intrinsic *offense* in doing so.

And aurman is still (per @polygamma's development decision) not going to include a special mode just to list available updates. It already contains a generic tool for describing, in json, the full details of an available update... and apparently nothing further is intended. This json is entirely parseable by any json parser (e.g. the shell command jq), aurman does not need to include something additionally parseable as line-by-line plaintext by the `wc -l` command.

**Comment by wjstarrsiii** [comment]
All is understood, thanks. I have no issue parsing json, I just don't like running scripts with elevated privileges when they are not going to make any changes to my system. I will look elsewhere for my ideal helper, thanks.

**Comment by polygamma** [comment]
okay then.

**Comment by eli-schwartz** [comment]
I'm a bit confused, why are you required to run aurman or aurmansolver with elevated privileges?

**Comment by wjstarrsiii** [comment]
I had not tried to run aurmansolver -Su yet.  I was running aurman -Su which them immediately prompts for a sudo password.  It appears that aurmansolver -Su will do what I need.  I appreciate your constructive feedback, @eli-schwartz.

**Comment by polygamma** [comment]
ROFL
