### ISSUE TITLE
Octopi integration

### ISSUE THREAD

**Issue by yarons** [polygamma/aurman#197]
Some posts on the Manjaro forum claimed that although this AUR Helper is a total kickass it lacks an Octopi integration.
https://octopiproject.wordpress.com/

Is that on the roadmap?

Thanks for all your work!

**Comment by eli-schwartz** [comment]
That's a horrifying idea. octopi does partial updates, which is explicitly unsupported in the strongest terms by the Arch Linux community.

Also Arch Linux is not Manjaro, and aurman does not target Manjaro users. Octopi is... not really used outside of Manjaro.

...

Also aurman is run via the command line, it would be quite weird for it to pop up a GUI to do official repo updates before falling back to the command line again for the AUR.

Also aurman explicitly does not support anything but pacman itself, and octopi is no better or worse than anything else that *isn't pacman*.
(Except in my mind, where Octopi will always be worse just because, well, it's *octopi* :rofl:.)

**Comment by polygamma** [comment]
As pointed out by @eli-schwartz, that's really not a good idea.
