### ISSUE TITLE
Crashes if you have a version-generic SOCKS proxy URL set in an environment variable

### ISSUE THREAD

**Issue by thiagoshr** [polygamma/aurman#223]
## Description
Title is self-explanatory

## Expected Behavior
aurman should be able to try connecting using SOCKS 5 and, in case the connection fails, SOCKS 4.
Reasoning: Currently, most SOCKS proxies, including tor, use SOCKS 5. Some desktop environments, like MATE, won't let you specify which version your SOCKS proxy uses. All other network-aware applications - including pacman! - are able to function with a generic "socks://ip:port" url set.

## Current Behavior
Crashes with a stack trace. I'm attaching the output as a text file
[output.log](https://github.com/polygamma/aurman/files/2209354/output.log)

## Possible Solution
Try to open the connection as a socks 5 proxy by default. In case it fails, try opening it as a socks 4 proxy. I don't know if this is an upstream bug in the python libraries used, but this might be an acceptable workaround for the time being.
At least there could be a nice error message instead of a stack trace dump.

## Version of aurman you are using
2.16.9-1

## Steps to Reproduce
1. Using the MATE Desktop (or any other equivalent method), set your socks proxy as an URL in the format of "socks://ip:port". You can export the environment variables "all_proxy" and "ALL_PROXY" in your test shell for this purpose;
2. Invoke "aurman -Syu";
3. Crashes!

## Read the README
Yes, I've read the README and it doesn't mention proxies.

## Running linux distribution
Arch Linux, up to date.

**Comment by polygamma** [comment]
What happens if you specify the correct socks version in your env vars? e. g. socks5 instead of only socks

**Comment by eli-schwartz** [comment]
Socks support should be natively available from requests and not involve the software which merely uses requests, surely?

**Comment by polygamma** [comment]
https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/socks.py#L159

**Comment by polygamma** [comment]
Conclusion: I do not want to implement proxy behavior manually, obviously the urllib devs decided not to assume or try something, when specifying "socks" only. I guess they have good reasons for that, if you want to know which, you should ask them. You can simply get it to work via exporting the env vars with the exact socks version specified when running `aurman`. e.g. `ALL_PROXY="socks4://ip:port" aurman -Syu`. To not do it all over again, just use an alias. I also do not want to cover the stacktrace, because it's the stacktrace of `python-requests`.
