### ISSUE TITLE
Recognize file:// or local:// sources in PKGBUILD and prompt user to download the file manually

### ISSUE THREAD

**Issue by Cysioland** [polygamma/aurman#225]
Some packages aren't permitted to package the necessary files, and require the user to download it manually (with an account, or accepting some kind of EULA). These packages use the download URL under the `url`, and `file://path/to/file` or `local://path/to/file` under `source`. It'd be nice if aurman, detecting such a condition, prompted the user with a text like:

_This package requires file download from an external URL: http://url.of/file_  
_Download filename.zip and place it in ~/.cache/aurman/package-name, then press ENTER_

**Comment by polygamma** [comment]
Explicit example, please.

**Comment by Cysioland** [comment]
https://aur.archlinux.org/packages/nvidia-sdk
https://aur.archlinux.org/packages/oracle-sqldeveloper/ (this one uses manual:// even)
https://aur.archlinux.org/packages/packettracer

**Comment by Cysioland** [comment]
Ideally, the user reads the full PKGBUILD only once, and then reads the diffs. Should user remember, which packages require manual intervention?

**Comment by eli-schwartz** [comment]
`makepkg` supports a number of download protocols, including git, svn, http, ftp, https, scp, and file://

In the event that a protocol is not known, it will skip trying to download the file.

In the event that the "special" url local:// is used, makepkg will not try to find an url handler to download with.

local:// urls are typically used on the AUR for files which are proprietary and guarded by e.g. a login page, since the user needs to download this by hand and copy into the PKGBUILD directory due to the distribution process of the package upstream.

(If an AUR package uses file:// for this they are doing it wrong plus makepkg now tries to use curl for this.)

**Comment by Cysioland** [comment]
@eli-schwartz Yeah, actually had to amend file:// to local:// because it failed to build the `nvidia-sdk`.

Maybe that's the way to go? Keep the list of "known" protocols, and in case of a protocol being unknown prompt the user to at least look into it.

**Comment by polygamma** [comment]
I actually really do not want to implement this kind of behavior, it's a really, really rare use case and for that I do not want to implement extra logic, sorry.

**Comment by eli-schwartz** [comment]
Known protocols are whatever the user lists in makepkg.conf, which by default includes the common ones and that default list now includes file://

**Comment by Cysioland** [comment]
@polygamma So maybe list this as "help wanted"?

**Comment by polygamma** [comment]
No, I'd also not merge a PR implementing it. It's nothing I want to have as feature in `aurman`. All about this is hacky, I do not want to provide logic to try to detect those things, it really comes down to: Read the PKGBUILD, in every case. A warning does not change anything about that.

**Comment by eli-schwartz** [comment]
IMO the user already has a chance to download and copy the file when they are prompted to read the package. The only thing aurman could do is print the directory you need to copy it into...
