### ISSUE TITLE
Allow passing '-w' to pacman

### ISSUE THREAD

**Issue by Ape** [polygamma/aurman#242]
`pacman -S` has option `-w, --downloadonly`. I would like to be able to use that option with aurman. E.g. so that `aurman -Syuw` works.

**Comment by polygamma** [comment]
Hm. I am not sure about this. It actually requires new logic to handle this properly, also what to do with AUR packages in such cases? Only clone the AUR git repo or completely download the needed sources?

**Comment by eli-schwartz** [comment]
Build the packages and assume the user set $PKGDEST, but not install them?

**Comment by polygamma** [comment]
Building may not be possible, because the dependencies may have been downloaded only

**Comment by Morganamilo** [comment]
From the pacaur manpage for -Sw, if you wish to implement the same.

```
buildonly
           Clone build files and build target(s). Missing dependencies will be
           installed as needed for the build process, and removed automatically
           afterwards.
```

**Comment by polygamma** [comment]
Another thing: Why would one want to use such feature in the first place? I've never used such an option, and I can't figure out how this could be useful

**Comment by eli-schwartz** [comment]
Well, it can make a lot of sense for binary repository packages since you can download them when you have (fast? unmetered?) internet and install them later when you have time to make sure the update is successful and doesn't cause issues with e.g. news items.

There isn't quite as much utility for extending this to the AUR, since you'd want to build against the new versions of updated packages...

And it's not like aurman really supports offline builds. Maybe if it were building in a clean chroot.

**Comment by polygamma** [comment]
I guess in that case, one may simply use `pacman` itself

**Comment by polygamma** [comment]
closing because of no further reply of @Ape
