### ISSUE TITLE
aurman produces with a bash prompt printed in bold

### ISSUE THREAD

**Issue by stefanhusmann** [polygamma/aurman#26]
After aurman says "Everything is up to date" my bash prompt is printed in bold and stays so. I think this should not be.

I use st terminal together with gnu screen, if that matters.

**Comment by polygamma** [comment]
Hey!

That's an issue with st, since it does not recognize `\e[21m` to reset bold. Compare with: https://misc.flogisoft.com/bash/tip_colors_and_formatting#terminals_compatibility

Should really be supported, hence that is not a bug of aurman.

**Comment by stefanhusmann** [comment]
Sorry I do not agree. According to Wikipedia \e[21m is not widely used in terminals, and terminfo has no name for it. See http://comptechdoc.org/os/linux/howlinuxworks/linux_hltermcommands.html
So you might reconsider this. 

For me I solved this with replacing \e[21m by \e[0m. Works fine so far.

**Comment by polygamma** [comment]
Well, `\e[0m` is not a solution for the problem, since that does something else than `\e[21m`. 
The first one resets **all** attributes, including color. So e.g. I want to print a green string:
"I am green" with the "am" as "bold". Finishing "am" with `\e[0m` instead of `\e[21m` would also reset the green color, which is not what I want.

I am calling things like this in my python code:
`Colors.GREEN("I {} green".format(Colors.BOLD("am")))`

Maybe there is a nice of way of handling that without the use of `\e[21m`, then I change it. But that means: No change of the code usages of Colors.BOLD, just the function behind it. If you know something, let me know, otherwise, I am not going to change anything about that.

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/9512cb40d66e64ed828612119cd50cb82720b334
