### ISSUE TITLE
Zsh, Fish completion?

### ISSUE THREAD

**Issue by Mauladen** [polygamma/aurman#35]
Do you plan to add completions for Zsh and Fish? 

- [ ] Completions for ZSH 
- [X] Completions for Fish

**Comment by polygamma** [comment]
As with the translation: Feel free to implement it, but it's nothing which I am going to do

**Comment by ChuckDaniels87** [comment]
It seems that Fish completion is a bit easier to implement compared to Zsh. At least in the way Bash completion have been implemented in this project.

**Comment by Mauladen** [comment]
I think will learn as well to make ZSH and send PR

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/pull/65

One fish user here who is able to give feedback?

**Comment by polygamma** [comment]
Fish completion has been added

**Comment by oberien** [comment]
@Mauladen Have you gotten around trying to add zsh completions?

**Comment by Mauladen** [comment]
@oberien No, but I think as time goes on, I didn't think it would and it would take that long.

**Comment by Alveel** [comment]
I should give fish a try :)

But would be great to see zsh completion.

**Comment by Mauladen** [comment]
@oberien I added a TODO

**Comment by coder-hugo** [comment]
I'm currently a user of `pacaur` which unfortunately isn't maintained anymore. So I plan to switch to `aurman`. But for this it would be nice to have a zsh completion. After a short look to the README I'd say that the syntax of `aurman` is pretty similar to the syntax of `pacaur`. So I think a good starting point to implement zsh completion is the [zsh completion of pacaur](https://github.com/rmarquis/pacaur/blob/master/zsh.completion).

**Comment by jsaalfeld** [comment]
I just checked up on @coder-hugo suggestion and took the https://github.com/rmarquis/pacaur/blob/master/zsh.completion file. These were my steps:

1. ```cd /usr/share/zsh/site-functions/```
2. ```sudo wget -O _aurman https://raw.githubusercontent.com/rmarquis/pacaur/master/zsh.completion```
3. ```sudo sed -i "s/pacaur/aurman/" _aurman```
4. ```sudo chmod 644 _aurman```

and so far, it seems to work fine!

**Comment by polygamma** [comment]
Depends on how you define "fine"

**Comment by jsaalfeld** [comment]
The basic tasks work fine (like extending parameters and tab-completion on package-names) and provide context. Most cases are the same, but there are some extensions that are wrong. I will update the PR according to the parameters of aurman.

**Comment by polygamma** [comment]
do not forget that aurman does not depend on cower

**Comment by jsaalfeld** [comment]
From that comment I'll guess that you won't be happy about that dependency?

**Comment by polygamma** [comment]
cower is a big deal because of only being available in the AUR. e. g. I am waiting with a new aurman release because of a commit aurman needs only being available with expac-git, not with expac. expac being in the repos, expac-git AUR.

**Comment by polygamma** [comment]
@jsaalfeld - you may use the existing infrastructure I am using for the `bash-completion`. e.g.
`aurman --auto_complete --auto_complete_cur aurm --auto_complete_index 2 --auto_complete_line aurman -Su aurm` yields `aurman aurman-git`

see also: https://github.com/polygamma/aurman/blob/master/bash.completion and https://github.com/polygamma/aurman/blob/master/src/aurman/bash_completion.py

all in all you can simply call aurman instead of cower to receive aur packages names.

**Comment by polygamma** [comment]
Just curious: There have been a few people over time, who told that they wanted to implement it. Any progress?

**Comment by jsaalfeld** [comment]
This issue is still on my radar, due to other circumstances it has to wait for a couple of weeks, I hope to start making progress on this in september.

**Comment by polygamma** [comment]
I guess you still want to include the `cower` dependency.

**Comment by steven-omaha** [comment]
Thanks, did it.

**Comment by francoism90** [comment]
@steven-omaha @polygamma Would it be possible to replace `cower` with a native solution as seen in https://github.com/polygamma/aurman/issues/35#issuecomment-396384194 :)

**Comment by steven-omaha** [comment]
@francoism90 It should definitely be possible. But I'm not interested to do this because my quick and dirty solution works for me. @polygamma is probably not interested because he uses bash. If you know zsh, feel free to give it a go!

**Comment by polygamma** [comment]
I am indeed using `bash` and thus not interested in implementing this. But I already wrote in the comment #35 you quoted, how to replace `cower` by the native `aurman` solution, so I do not quite understand your question to be honest

**Comment by francoism90** [comment]
@polygamma Sorry, I was just asking if it would be possible and if `cower` could be ditched. I'll try to look into it when I have the time. :)

**Comment by polygamma** [comment]
Yeah, `cower` can be ditched, I coded the needed infrastracture in `aurman` itself, including everything, not only fetching names of AUR packages. It's quite a hack, but also very elegant. Look at the following line from the bash completion file: https://github.com/polygamma/aurman/blob/master/bash.completion#L11

`aurman` itself gets called from the bash completion, the relevant `aurman` sourcecode is here: https://github.com/polygamma/aurman/blob/master/src/aurman/bash_completion.py

See e.g.
```
[jonny@jonny-arch-pc ~]$ aurman --auto_complete --auto_complete_cur aurm --auto_complete_index 2 --auto_complete_line aurman -Su aurm
aurman-zsh-completion aurman-git aurman
```

**Comment by steven-omaha** [comment]
Using `aurman` itself for completion is indeed quite charming, since there's no need to update external completion functions for three different shells. The downside is execution speed. 
```
~ $ time aurman
2018-08-07 13:33:51,826 - parse_args - parse_pacman_args - ERROR - No operation defined
:: aurman --help or aurman -h
aurman  0,23s user 0,02s system 99% cpu 0,258 total

~ $ time aurman --auto_complete --auto_complete_cur aurm --auto_complete_index 2 --auto_complete_line aurman -S aurm
aurman-zsh-completion aurman-git aurman
aurman --auto_complete --auto_complete_cur aurm --auto_complete_index 2   -S   0,39s user 0,03s system 36% cpu 1,148 total
```
That is 0.25 seconds for calling `aurman` (not once, but for every argument that you want to complete) and addtionally about 0.75 seconds for every package. This is probably okay for just completing one or two package names when you (for example) forgot the ending of the package name, but for more complicated tasks, like specifiying `-S --pgp_fetch --keyserver [...] --always_edit packageA packageB` this gets time-consuming pretty quickly. 

In contrast, the more elaborate solution from `pacaur` has a tremendous amount of code, but is an order of magnitude faster. 

I would personally prefer the latter way to solve this. Maybe the best (maybe over-engineered?) solution would be to derive the `zsh` argument completion definition from `aurman`'s code itself, and cache the list of package names in the shell's cache.

Unfortunately, this goes much over my understanding of `zsh`.

**Comment by eli-schwartz** [comment]
It should be possible to generate the options and only use aurman for completing the actual package names; I'd encourage doing this for every shell. ;)

**Comment by polygamma** [comment]
@eli-schwartz, it would definitely be nice, but I am not the one, who is going to implement that :D
