### ISSUE TITLE
dashes instead of underscores in option names

### ISSUE THREAD

**Issue by anntzer** [polygamma/aurman#56]
It is near-universal to use dashes instead of underscores in option names (see e.g. pacman itself: --print-format).  The stdlib's argparse even contains the provision that "dest will be derived from the first short option string by stripping the initial - character. Any internal - characters will be converted to _ characters to make sure the string is a valid attribute name."  (any reason you are not using argparse, by the way?  just curious)
It would be nice if aurman followed the same convention.

**Comment by polygamma** [comment]
i do not use argparse because i wanted to use the parsed args in a special way, hence i wrote my own parser. you may be right about the dashes, but i am not going to change that, just to fulfill this convention. if i had known about that earlier, i had done it right, but that's nothing which i am going to change now
