### ISSUE TITLE
Check disk usage & package size (Feature Request)

### ISSUE THREAD

**Issue by hubitor** [polygamma/aurman#66]
I've installed aurman on a Arch VM with a small home partition (~ 6GB) for testing purposes and created a script to automate installation. After some time aurman was giving errors like "ERROR - Creating package dir of <package> failed". I then found out that it was because the home partition was full. In a script one could of course check the remaining disk space but maybe it would still be a good idea that aurman itself somehow informs the user about the remaining disk space or even if possible about how much space is needed for a specific package.

**Comment by frealgagu** [comment]
It's not possible to know how much space a package will need because it depends of the build process in PKGBUILD, pacman knows how much the .tar.xz occupies and how much compression ratio it has, but the build process is a lot more complicated to know. If that characteristic need to be implemented, it should be at the side of the aur scripts and not at the side of an aur helper which is just a package manager wrapper with aur building capabilities.

**Comment by polygamma** [comment]
@frealgagu is right, this is nothing, which aurman should or could handle.
