### ISSUE TITLE
aurman -Syu is slow compared to pacaur -Syu

### ISSUE THREAD

**Issue by protist** [polygamma/aurman#70]
## Description
I timed `aurman -Syu` and `pacaur -Syu`, and aurman is much slower. I alternated commands in five independent tests. On my system, aurman has a mean of 2.5 s, and pacaur has a mean of 6.1 s (std dev <0.07 in both cases). This means `aurman -Syu` is 2.4 times as slow as `pacaur -Syu`. This was tested with no packages needing updates.

## Expected Behavior
aurman should be a similar speed to pacaur.

## Current Behavior
aurman is 2.4 times slower than pacaur.

## Possible Solution
I'm not sure how both programs implement this command, but presumably there is room for optimisation with aurman.

## Steps to Reproduce
1. `for i in {1..5}; do time pacaur -Syu; time aurman -Syu; done`
2. Extract total times and compare.

**Comment by protist** [comment]
I just tested `sudo bauerbill -Syu --aur`, and it took 2.1 s on average (std dev 0.03), although I didn't alternate this time, so network congestion might play a small role.

**Comment by polygamma** [comment]
Sorry, without a concrete suggestion from your side, what's wrong, I'm not gonna investigate here, since it really is irrelevant.

**Comment by polygamma** [comment]
addition: this "problem" is only about the startup process, but since aurman does a bit more than pacaur, e.g. parsing of pacman.conf for own user repositories, fetching all needed upstream repo information before it is needed etc. that's just how it is. dependency solving, fetching PKGBUILDs etc. is much faster with aurman, hence it really is irrelevant, I am closing this issue, if you want it to be reopened, be more concrete about the problem

**Comment by polygamma** [comment]
Well, to be able to talk about "optimization", one has to be very clear about what exactly is being done and how this could be done faster. Just measuring the execution time, without stating what exactly is being done, does not yield any useful information. I've shifted some calculations and information gathering in comparison to other aur helpers like pacaur. This may seem like "overhead" when there is actually nothing to be done, but in order to be able to tell, that there "really" is nothing to be done, many things have to be known . If you are interested in what aurman actually does, the main.py contains the whole "logic", and in the wiki in this github repo is an article about the dependency solving of aurman.
Nevertheless: Thank you very much for the kind words!

**Comment by protist** [comment]
Ah, got it. Thank you for the references. That make much more sense, and it's now clear why there is a difference in duration compared to pacaur. Cheers and thanks again.
