### ISSUE TITLE
propagate error messages from wrappers + better debug

### ISSUE THREAD

**Issue by cptMikky** [polygamma/aurman#71]
Currently, to my knowledge, there is no way to make aurman report what error was given by a wrapper. In my case I can't troubleshoot a problem with AUR install.

On each and every AUR package I get
```
2018-04-19 18:35:45,608 - wrappers - makepkg - ERROR - makepkg query makepkg --printsrcinfo failed
```
which isn't very useful.

I'd like to see what error did makepkg give and better yet, what steps have been taken so far and if they succeeded or failed.

**Comment by polygamma** [comment]
Issue template.

**Comment by cptMikky** [comment]
This is a feature request, I don't seek to find the solution to the makepkg problem here.

**Comment by polygamma** [comment]
Okay, you should still be more precise about what *exactly* you want.
Stacktraces etc. are not useful in those cases, since the problem is a makepkg one, and normal makepkg calls print enough information. This --printsrcinfo thing is for something special, and if that fails, you almost likely have not read the arch wiki article about the AUR and have not installed "base-devel"

**Comment by cptMikky** [comment]
>  I'd like to see what error did makepkg give

**Comment by polygamma** [comment]
I agree, this *may* be useful, but I am not going to change that by myself, since regular makepkg commands give enough output, and things like that --printsrcinfo command only fail if the user has not been able to configure his system in a proper way. If you submit a well written PR, which tackles the output, go for it, I'd merge that, but besides that: I am not going to implement this

**Comment by kwshi** [comment]
The issue is perhaps not quite as simple as "I didn't install `base-devel`".  As an example, I've encountered this error while trying to (re)install `gcc6` via the AUR.  Here's what happens:
```
$ aurman -S gcc6
~~ initializing aurman...
~~ calculating solutions...

:: The following 7 package(s) are getting installed:
   extra/apr           /          ->  1.6.3-1
   extra/apr-util      /          ->  1.6.1-2
   extra/dejagnu       /          ->  1.6.1-1
   extra/doxygen       /          ->  1.8.14-1
   extra/expect        /          ->  5.45.4-1
   extra/serf          /          ->  1.3.9-2
   extra/subversion    /          ->  1.9.7-4

:: The following 1 package(s) are getting reinstalled:
   aur/gcc6            6.4.1-5    ->  6.4.1-5

?? Do you want to continue? Y/n: y
~~ looking for new pkgbuilds and fetch them...
Cloning into 'gcc6'...
remote: Counting objects: 47, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 47 (delta 10), reused 46 (delta 9)
Unpacking objects: 100% (47/47), done.
?? Do you want to see the changes of gcc6? N/y: n
2018-05-25 00:32:07,931 - wrappers - makepkg - ERROR - makepkg query makepkg --printsrcinfo failed
```
Here's what (the now inactive) pacaur says when I try to do the same thing:
```
$ pacaur -y gcc6
:: resolving dependencies...
:: looking for inter-conflicts...
:: gcc6-6.4.1-5 is up to date -- reinstalling

AUR Packages  (1) gcc6-6.4.1-5  
Repo Packages (7) apr-1.6.3-1  apr-util-1.6.1-2  dejagnu-1.6.1-1  doxygen-1.8.14-1  expect-5.45.4-1  serf-1.3.9-2  subversion-1.9.7-4  

Repo Download Size:   10.67 MiB
Repo Installed Size:  50.71 MiB

:: Proceed with installation? [Y/n] 

:: Retrieving package(s)...
:: gcc6 build files are up-to-date -- skipping
:: Checking gcc6 integrity...
==> ERROR: Cannot find the subversion package needed to handle svn sources.

==> ERROR: An unknown error has occurred. Exiting...
:: failed to verify gcc6 integrity
```

The problem seems to be that `gcc6` requires sources to be fetched from an SVN repository, and SVN is not installed on my computer.  Your point about `base-devel` not being installed does not stand, because SVN is not included in the `base-devel` group (as much as one might expect it to be).  indeed, aurman successfully installs `gcc6` once I also manually install `subversion`.  

It is worth noting that `gcc6` *does* list `svn` as one of its make-dependencies, seemingly expecting that doing so would allow `svn` to be installed prior to sources being fetched for `gcc6`.  Evidently, pacaur and aurman seem to make the assumption that make-dependencies are only used during the build process, and not during the source-fetching process, and so makepkg fails when it attempts to fetch sources before the make-dependencies have been installed.

It's a different question as to what the "correct" expectation should be.  Is it unfair for the `gcc6` PKGBUILD to assume that make-dependencies are installed before sources are fetched?  If so, here are some possible resolutions:

- `makepkg` should depend on `svn`
- `svn` should be included in `base-devel`
- `aurman` should depend on `svn`.  This solution, I suspect, is most preferred, because it appears to be the same way `aurman` currently ensures that it is able to fetch git sources.

On the other hand, if it is fair for `gcc6` to assume that make-dependencies are installed before sources are fetched, then accordingly aurman should install all make-dependencies before even fetching AUR sources.

Finally, there is the question, which is the topic of this thread, of whether error messages should be propagated from wrapped commands.  My opinion is yes.  While in an ideal setting any correctly configured Arch setup *should not* face problems with getting `makepkg` to work as intended, things are not always ideal (as evidenced by this `gcc6` case), and having error message propagation---as pacaur does---saves a lot of headache by identifying the problem quickly and pinpointing what sort of action to take---be it on aurman's part or on the Arch devs' part---in order to address these unexpected bugs.  Perhaps OP has indeed done something wrong if *all* their AUR packages are failing, but the point stands that edge cases like `gcc6` exist, and in these situations it would be very helpful to have error messages be propagated from wrapped commands to facilitate in debugging.  In this case, aurman's output alone clearly gives no indication of where the error source is, while pacaur's output immediately identifies the missing piece.  The benefits of having such a feature really are prominent, and so perhaps it should not be so casually dismissed.

**Comment by polygamma** [comment]
error messages from makepkg are being printed now. see: https://github.com/polygamma/aurman/commit/4f539266ecc52abdb5a6d5d86a7486fd6f01b118
