### ISSUE TITLE
Install all generated AUR packages at once whenever possible

### ISSUE THREAD

**Issue by jdemilledt** [polygamma/aurman#76]
I know this would be hard, so I'm willing to help implement it.

Could it be made that aurman would install as many of the generated AUR packages it can at once?
For example, if an AUR package has an AUR build dependency and an AUR runtime dependency, the build dependency would be built first (in the same way I'm describing), and installed. Then, the runtime dependency and the main package are installed in one transaction.

**Comment by polygamma** [comment]
I was also thinking about that already, but as you wrote, it's not "that easy".
Currently I don't have the time for such things, I planned to implement such things after the term of university is over, which would be around the beginning of july.

Dependency solving does not need to be changed, but the the calculation of the "package chunks", in which to install the packages.
Also does one need to change how to install aur packages, since it is currently only possible to install aur packages one by one.

**Comment by polygamma** [comment]
installing of packages: https://github.com/polygamma/aurman/blob/2.9.24/src/aurman/main.py#L477
chunks calculation: https://github.com/polygamma/aurman/blob/2.9.24/src/aurman/classes.py#L1406

**Comment by jdemilledt** [comment]
AUR packages can be built to `.pkg.tar<ext>` files, so they could be outputted to some aurman directory where packages ready for install can wait

**Comment by polygamma** [comment]
Sorry, it seems like you have no idea what aurman even does

**Comment by polygamma** [comment]
I've thought in detail about this feature, and it is only a good idea at first thought.
In order to be able to build an AUR package, **all** dependencies need to be **installed**. Normal dependencies, make dependencies and check dependencies. Hence there can't exist the case, where you install a *runtime* dependency and the package itself together, since you need the dependency installed to build the package itself. This feature would only give benefits for split packages, since that's a case where multiple packages are being built at once. You could install those split packages together with one command, but that's it. It would also change dependency solving, despite what I said first, and would make that much more complicated. It also has other more complicated downsides - all in all: I am not going to support this, sorry. But thanks for the suggestion

**Comment by frealgagu** [comment]
Actually what pacaur does is not to ask about the packages installation at the end, instead it assumes the first confirmation as valid and install each package as soon as built. However pacaur has the possibility to know beforehand what packages are going to be installed and to ask to user at the beginning in order to install everything without additional user confirmation.

I don't know if aurman has the option to not ask at the end and if - - noedit and - - noconfirm has this purpose (in order to let aurman install a bunch of packages which require time and you don't want to wait per each one to press enter once have been built).
