### ISSUE TITLE
Feature/Enhancement request: call makepkg with the -r option

### ISSUE THREAD

**Issue by Taijian** [polygamma/aurman#95]
Hi, it's me again with another feature request! :)

I was wondering whether you could implement the option to have aurman call makepkg with the -r (--remove) option, so that make-depends that get installed as part of the building process can automagically be removed again, once the AUR package has finished building. 

This should be fairly easy to implement, as it is really just about passing another parameter to makepkg (which I assume aurman uses anyway to parse PKGBUILDs).

Thank you!

**Comment by polygamma** [comment]
Sorry, aurman is not using dependency auto-resolution (makepkg -s). but you may imvoke `pacman -Rns $(pacman -Qtdq)` to remove orphans after installation has finished

**Comment by Ape** [comment]
Would you consider adding an option to automatically removing the orphans after installation?

**Comment by polygamma** [comment]
Would there be any benefit in a command line flag for `aurman` instead of invoking `pacman -Rns $(pacman -Qtdq)`?

**Comment by Ape** [comment]
Well, it's only a matter of convenience. It would be easier for me to only call one command instead of two. I would like to clean up the orphans everytime I do `aurman -Syu`. Maybe the best solution for me would be a configuration option in aurman.

**Comment by Taijian** [comment]
This!

**Comment by polygamma** [comment]
I've thought about this and I am not going to implement that. `pacman -R` is a potentially destructive option, which shouldn't be run just after every installation, you may just use a bash alias if you want to accomplish that. I also don't want to support it via the config, since it yields more questions about whether to use `--noconfirm`, `-n` etc. Just decide that for yourself with an alias
