### ISSUE TITLE
Invalid config file options are not flagged

### ISSUE THREAD

**Issue by HaleTom** [polygamma/aurman#99]
## Description
Invalid config file options do not trigger a warning / error message

## Expected Behavior
I get a message with the offending unsupported option

## Current Behavior
I get no message as expected

## Possible Solution
Unknown

## Steps to Reproduce

```
$ cat $XDG_CONFIG_HOME/aurman/aurman_config
[miscellaneous]
default_show_changes
keyserver=hkp://ipv4.pool.sks-keyservers.net:11371
optimistic_versioning
fdsakflasd
```

**Comment by polygamma** [comment]
Will be changed, but no ETA since it is quite irrelevant

**Comment by polygamma** [comment]
I am not going to implement this by myself, because one needs to maintain a list of the currently valid config options. The options are listed in the README, which is always up-to-date, I guess there really is no need to implement this. If one really wants to have that, implement that in a sensible way and open a PR.
